apiVersion: v1
kind: Pod
metadata:
  name: aegis-tester
  labels:
    app: aegis-tester
spec:
  containers:
    - name: tester
      image: appropriate/curl
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          while true; do
            curl -v 1 -sSf http://aegis:80/ready || exit 1;
            sleep 10;
          done
  restartPolicy: Always