/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Go JWT Server
 * OpenAPI spec version: 1.0.0
 */
export interface OAuthError {
  error: string;
  error_description?: string;
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token?: string;
  scope?: string;
}

export interface IntrospectionResponse {
  active: boolean;
  sub?: string;
  client_id?: string;
  scope?: string;
  exp?: number;
  iat?: number;
  iss?: string;
  aud?: string;
  jti?: string;
  token_type?: string;
}

export interface UserSignup {
  email: string;
  firstName: string;
  lastName: string;
  /**
   * At least 8 characters, one uppercase, one lowercase, one number, one special character
   * @minLength 8
   */
  password: string;
  twoFAEnabled: boolean;
}

export interface SignUpWith2FAResponse {
  qr_image: string;
  secret: string;
}

export interface UserLogin {
  email: string;
  password: string;
}

export interface ChangePassword {
  oldPassword: string;
  newPassword: string;
  /** @pattern ^\d{6}$ */
  twoFACode?: string;
}

export interface LoginSuccessWithJWT {
  accessToken: string;
  refreshToken: string;
}

export type LoginRequires2FAType = typeof LoginRequires2FAType[keyof typeof LoginRequires2FAType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginRequires2FAType = {
  '2fa': '2fa',
} as const;

export interface LoginRequires2FA {
  type: LoginRequires2FAType;
  /** Temporary token to use for 2FA verification */
  temp_token: string;
}

export interface Refresh {
  refreshToken: string;
}

export interface RevokeCurrentSession {
  refreshToken: string;
}

export interface GetAllSessionResponse {
  issuedAt: string;
  expiresAt: string;
  ipAddress: string;
  userAgent: string;
  createdBy: string;
}

export interface TwoFAResponse {
  qr_image: string;
  secret: string;
}

export interface Login2FARequest {
  /** @pattern ^\d{6}$ */
  twoFACode: string;
}

export interface Remove2FARequest {
  /** @pattern ^\d{6}$ */
  twoFACode: string;
}

export interface CreateRole {
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
}

export interface UpdateRole {
  /** @pattern [a-zA-Z_-]+ */
  name?: string;
  description?: string;
}

export interface CreatePermission {
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
}

export interface UpdatePermission {
  /** @pattern [a-zA-Z_-]+ */
  name?: string;
  description?: string;
}

export interface RoleResponse {
  id: number;
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
}

export interface PermissionResponse {
  id: number;
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
}

export interface AssignPermission {
  ids: number[];
}

export type RolesAndPermissionResponseRoles = {
  id: number;
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
  permissions: PermissionResponse[];
};

export interface RolesAndPermissionResponse {
  roles: RolesAndPermissionResponseRoles;
}

export interface UserWithRoles {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
  permissions: string[];
}

export interface AssignRoleToUser {
  roles: number[];
}

export interface UserDetails {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  locked: boolean;
  disabled: boolean;
  twoFAEnabled: boolean;
  createdAt: string;
  updatedAt: string;
  roles: string[];
  permissions: string[];
}

export interface UserDetailsRole {
  id: number;
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
}

export interface UserDetailsPermission {
  id: number;
  /** @pattern [a-zA-Z_-]+ */
  name: string;
  description: string;
}

export type LoginSourceParameter = typeof LoginSourceParameter[keyof typeof LoginSourceParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginSourceParameter = {
  web: 'web',
  mobile: 'mobile',
  api: 'api',
} as const;

/**
 * User Agent
 */
export type UserAgentParameter = string;

/**
 * name
 */
export type GETNameParameter = string;

export type Login200 = LoginSuccessWithJWT | LoginRequires2FA;

export type GetListOfUsersParams = {
/**
 * Enter the first name of the user you want to search
 */
firstName?: string;
/**
 * Enter the first name of the user you want to search
 */
lastName?: string;
/**
 * Enter the first name of the user you want to search
 */
email?: string;
/**
 * Enter the first name of the user you want to search
 */
size?: number;
/**
 * Enter the first name of the user you want to search
 */
page?: number;
};

/**
 * Endpoint for user signup
 * @summary User signup
 */
export const getSignupUrl = () => {


  

  return `/api/v1/auth/signup`
}

export const signup = async (userSignup: UserSignup, options?: RequestInit): Promise<SignUpWith2FAResponse | void> => {
  
  const res = await fetch(getSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSignup,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: SignUpWith2FAResponse | void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint for user login
 * @summary User login
 */
export const getLoginUrl = () => {


  

  return `/api/v1/auth/login`
}

export const login = async (userLogin: UserLogin, options?: RequestInit): Promise<Login200> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userLogin,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: Login200 = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to change password
 * @summary Change password
 */
export const getChangePasswordUrl = () => {


  

  return `/api/v1/auth/password`
}

export const changePassword = async (changePassword: ChangePassword, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePassword,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to get new token using refresh token
 * @summary Token refresh
 */
export const getRefreshUrl = () => {


  

  return `/api/v1/auth/refresh`
}

export const refresh = async (refresh: Refresh, options?: RequestInit): Promise<LoginSuccessWithJWT> => {
  
  const res = await fetch(getRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refresh,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LoginSuccessWithJWT = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to get all active sessions of a given user
 * @summary Get all sessions
 */
export const getGetAllSessionsUrl = () => {


  

  return `/api/v1/auth/sessions`
}

export const getAllSessions = async ( options?: RequestInit): Promise<GetAllSessionResponse[]> => {
  
  const res = await fetch(getGetAllSessionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: GetAllSessionResponse[] = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to revoke all refresh tokens of a user
 * @summary Revoke all refresh tokens
 */
export const getRevokeAllTokensUrl = () => {


  

  return `/api/v1/auth/sessions`
}

export const revokeAllTokens = async ( options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getRevokeAllTokensUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to revoke single refresh token
 * @summary Revoke refresh token
 */
export const getRevokeRefreshTokenUrl = () => {


  

  return `/api/v1/auth/sessions/current`
}

export const revokeRefreshToken = async (revokeCurrentSession: RevokeCurrentSession, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getRevokeRefreshTokenUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      revokeCurrentSession,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to create 2fa for a user
 * @summary Create 2fa
 */
export const getCreate2FAUrl = () => {


  

  return `/api/v1/auth/2fa/setup`
}

export const create2FA = async ( options?: RequestInit): Promise<TwoFAResponse> => {
  
  const res = await fetch(getCreate2FAUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: TwoFAResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to verify 2FA code of a user with temp_token to login and get bearer and refresh token
 * @summary Verify 2FA code and login
 */
export const getLogin2FAUrl = () => {


  

  return `/api/v1/auth/2fa/login`
}

export const login2FA = async (login2FARequest: Login2FARequest, options?: RequestInit): Promise<LoginSuccessWithJWT> => {
  
  const res = await fetch(getLogin2FAUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      login2FARequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: LoginSuccessWithJWT = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to remove 2fa code of a user
 * @summary Remove 2fa
 */
export const getRemove2FAUrl = () => {


  

  return `/api/v1/auth/2fa`
}

export const remove2FA = async (remove2FARequest: Remove2FARequest, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getRemove2FAUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      remove2FARequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to list all roles in the system
 * @summary List all roles
 */
export const getListAllRolesUrl = () => {


  

  return `/api/v1/access-control/roles`
}

export const listAllRoles = async ( options?: RequestInit): Promise<RoleResponse[]> => {
  
  const res = await fetch(getListAllRolesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: RoleResponse[] = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to create a new role
 * @summary Create a new role
 */
export const getCreateNewRoleUrl = () => {


  

  return `/api/v1/access-control/roles`
}

export const createNewRole = async (createRole: CreateRole, options?: RequestInit): Promise<RoleResponse> => {
  
  const res = await fetch(getCreateNewRoleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRole,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: RoleResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to Get role details by it's id
 * @summary Get role by ID
 */
export const getGetRoleByIdUrl = (roleId: number,) => {


  

  return `/api/v1/access-control/roles/${roleId}`
}

export const getRoleById = async (roleId: number, options?: RequestInit): Promise<RoleResponse> => {
  
  const res = await fetch(getGetRoleByIdUrl(roleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: RoleResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to update a role by it's ID
 * @summary Update role
 */
export const getUpdateRoleByIdUrl = (roleId: number,) => {


  

  return `/api/v1/access-control/roles/${roleId}`
}

export const updateRoleById = async (roleId: number,
    updateRole: UpdateRole, options?: RequestInit): Promise<RoleResponse> => {
  
  const res = await fetch(getUpdateRoleByIdUrl(roleId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRole,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: RoleResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to delete a role by it's ID
 * @summary Delete role
 */
export const getDeleteRoleByIdUrl = (roleId: number,) => {


  

  return `/api/v1/access-control/roles/${roleId}`
}

export const deleteRoleById = async (roleId: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeleteRoleByIdUrl(roleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to list all permissions in the system
 * @summary List all permissions
 */
export const getListAllPermissionsUrl = () => {


  

  return `/api/v1/access-control/permissions`
}

export const listAllPermissions = async ( options?: RequestInit): Promise<PermissionResponse[]> => {
  
  const res = await fetch(getListAllPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: PermissionResponse[] = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to create a new permission
 * @summary Create a new permission
 */
export const getCreateNewPermissionUrl = () => {


  

  return `/api/v1/access-control/permissions`
}

export const createNewPermission = async (createPermission: CreatePermission, options?: RequestInit): Promise<PermissionResponse> => {
  
  const res = await fetch(getCreateNewPermissionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPermission,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: PermissionResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to Get permission details by it's id
 * @summary Get permission by ID
 */
export const getGetPermissionByIdUrl = (id: number,) => {


  

  return `/api/v1/access-control/permissions/${id}`
}

export const getPermissionById = async (id: number, options?: RequestInit): Promise<PermissionResponse> => {
  
  const res = await fetch(getGetPermissionByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: PermissionResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to update a permission by it's ID
 * @summary Update permission
 */
export const getUpdatePermissionByIdUrl = (id: number,) => {


  

  return `/api/v1/access-control/permissions/${id}`
}

export const updatePermissionById = async (id: number,
    updatePermission: UpdatePermission, options?: RequestInit): Promise<PermissionResponse> => {
  
  const res = await fetch(getUpdatePermissionByIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePermission,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: PermissionResponse = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to delete a permission by it's ID
 * @summary Delete permission
 */
export const getDeletePermissionByIdUrl = (id: number,) => {


  

  return `/api/v1/access-control/permissions/${id}`
}

export const deletePermissionById = async (id: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDeletePermissionByIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * List of Roles and their assigned permissions
 * @summary Roles and their permissions
 */
export const getRolesAndPermissionsUrl = () => {


  

  return `/api/v1/access-control/roles/permissions`
}

export const rolesAndPermissions = async ( options?: RequestInit): Promise<RolesAndPermissionResponse[]> => {
  
  const res = await fetch(getRolesAndPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: RolesAndPermissionResponse[] = body ? JSON.parse(body) : {}
  return data
}



/**
 * Get a list of users with given filter
 * @summary Get list of users
 */
export const getGetListOfUsersUrl = (params?: GetListOfUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/users?${stringifiedParams}` : `/api/v1/users`
}

export const getListOfUsers = async (params?: GetListOfUsersParams, options?: RequestInit): Promise<UserDetails[]> => {
  
  const res = await fetch(getGetListOfUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: UserDetails[] = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to list roles of a user
 * @summary Get user's roles
 */
export const getGetRolesOfUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/roles`
}

export const getRolesOfUser = async (id: number, options?: RequestInit): Promise<UserWithRoles> => {
  
  const res = await fetch(getGetRolesOfUserUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: UserWithRoles = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to assign roles to a given user
 * @summary Assign roles to user
 */
export const getAssignRolesToUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/roles`
}

export const assignRolesToUser = async (id: number,
    assignRoleToUser: AssignRoleToUser, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getAssignRolesToUserUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignRoleToUser,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Locks a user account due to security reasons.
Locked users cannot authenticate until unlocked.

 * @summary Lock a user
 */
export const getLockUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/lock`
}

export const lockUser = async (id: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getLockUserUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Unlocks a previously locked user account.

 * @summary Unlock a user
 */
export const getUnlockUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/lock`
}

export const unlockUser = async (id: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getUnlockUserUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Disables a user account for administrative reasons.
Disabled users cannot authenticate until enabled.

 * @summary Disable user account
 */
export const getDisableUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/disable`
}

export const disableUser = async (id: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getDisableUserUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Re-enables a previously disabled user account.

 * @summary Enable user account
 */
export const getEnableUserUrl = (id: number,) => {


  

  return `/api/v1/users/${id}/enable`
}

export const enableUser = async (id: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getEnableUserUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Endpoint to remove roles of a user
 * @summary Remove roles of user
 */
export const getRemoveRolesForUserUrl = (id: number,
    roleId: number,) => {


  

  return `/api/v1/users/${id}/roles/${roleId}`
}

export const removeRolesForUser = async (id: number,
    roleId: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getRemoveRolesForUserUrl(id,roleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Assign multiple permissions to a role
 * @summary Assign permissions to a role
 */
export const getAssignPermissionToRoleUrl = (roleId: number,) => {


  

  return `/api/v1/access-control/roles/${roleId}/permissions`
}

export const assignPermissionToRole = async (roleId: number,
    assignPermission: AssignPermission, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getAssignPermissionToRoleUrl(roleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignPermission,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Unassign a permission from a role
 * @summary Unassign a permission from a role
 */
export const getUnassignPermissionFromRoleUrl = (roleId: number,
    permissionId: number,) => {


  

  return `/api/v1/access-control/roles/${roleId}/permissions/${permissionId}`
}

export const unassignPermissionFromRole = async (roleId: number,
    permissionId: number, options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getUnassignPermissionFromRoleUrl(roleId,permissionId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Ready check
 * @summary Ready check
 */
export const getGetReadyUrl = () => {


  

  return `/ready`
}

export const getReady = async ( options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getGetReadyUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}



/**
 * Live check
 * @summary Live check
 */
export const getGetLiveUrl = () => {


  

  return `/live`
}

export const getLive = async ( options?: RequestInit): Promise<void> => {
  
  const res = await fetch(getGetLiveUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: void = body ? JSON.parse(body) : {}
  return data
}
